MIN_INDENTATION = 0
MAX_INDENTATION = 10
DEFAULT_INDENTATION = 2
INDENTATION_ERR_MSG = "Indentation is out of range"
MIN_TEXT_CHANGE_DELAY = 0
MAX_TEXT_CHANGE_DELAY = 1000
DEFAULT_TEXT_CHANGE_DELAY = 100
TEXT_CHANGE_DELAY_ERR_MSG = "Text change delay is out of range"
